// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TicketManagement.WPF.WebAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RegisterResult
    {
        /// <summary>
        /// Initializes a new instance of the RegisterResult class.
        /// </summary>
        public RegisterResult() { }

        /// <summary>
        /// Initializes a new instance of the RegisterResult class.
        /// </summary>
        public RegisterResult(bool? successed = default(bool?), string userId = default(string))
        {
            Successed = successed;
            UserId = userId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "successed")]
        public bool? Successed { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

    }
}
