//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataEntity
{
    using System;
    
    public partial class GetUserCart_Result3
    {
        public int EventSeatId { get; set; }
        public int Number { get; set; }
        public int Row { get; set; }
        public string AreaDescription { get; set; }
        public decimal Price { get; set; }
        public string LayoutDescription { get; set; }
        public string VenueDescription { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }
}
