//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataEntity
{
    using System;
    
    public partial class VisibleEvents_Result2
    {
        public string Description { get; set; }
        public System.DateTime EventDate { get; set; }
        public int Id { get; set; }
        public int LayoutId { get; set; }
        public string Name { get; set; }
    }
}
