//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.WPF.WCF.LayoutService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Layout", Namespace="http://schemas.datacontract.org/2004/07/DataPresenter.Entity")]
    [System.SerializableAttribute()]
    public partial class Layout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VenueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((this.VenueIdField.Equals(value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.LayoutService.ILayoutService")]
    public interface ILayoutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Delete", ReplyAction="http://tempuri.org/ILayoutService/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Delete", ReplyAction="http://tempuri.org/ILayoutService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Get", ReplyAction="http://tempuri.org/ILayoutService/GetResponse")]
        TicketManagement.WPF.WCF.LayoutService.Layout Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Get", ReplyAction="http://tempuri.org/ILayoutService/GetResponse")]
        System.Threading.Tasks.Task<TicketManagement.WPF.WCF.LayoutService.Layout> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/GetAll", ReplyAction="http://tempuri.org/ILayoutService/GetAllResponse")]
        TicketManagement.WPF.WCF.LayoutService.Layout[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/GetAll", ReplyAction="http://tempuri.org/ILayoutService/GetAllResponse")]
        System.Threading.Tasks.Task<TicketManagement.WPF.WCF.LayoutService.Layout[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Save", ReplyAction="http://tempuri.org/ILayoutService/SaveResponse")]
        int Save(TicketManagement.WPF.WCF.LayoutService.Layout layout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Save", ReplyAction="http://tempuri.org/ILayoutService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(TicketManagement.WPF.WCF.LayoutService.Layout layout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Update", ReplyAction="http://tempuri.org/ILayoutService/UpdateResponse")]
        bool Update(TicketManagement.WPF.WCF.LayoutService.Layout layout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayoutService/Update", ReplyAction="http://tempuri.org/ILayoutService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(TicketManagement.WPF.WCF.LayoutService.Layout layout);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILayoutServiceChannel : TicketManagement.WPF.WCF.LayoutService.ILayoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LayoutServiceClient : System.ServiceModel.ClientBase<TicketManagement.WPF.WCF.LayoutService.ILayoutService>, TicketManagement.WPF.WCF.LayoutService.ILayoutService {
        
        public LayoutServiceClient() {
        }
        
        public LayoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LayoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LayoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LayoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public TicketManagement.WPF.WCF.LayoutService.Layout Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<TicketManagement.WPF.WCF.LayoutService.Layout> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public TicketManagement.WPF.WCF.LayoutService.Layout[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TicketManagement.WPF.WCF.LayoutService.Layout[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public int Save(TicketManagement.WPF.WCF.LayoutService.Layout layout) {
            return base.Channel.Save(layout);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(TicketManagement.WPF.WCF.LayoutService.Layout layout) {
            return base.Channel.SaveAsync(layout);
        }
        
        public bool Update(TicketManagement.WPF.WCF.LayoutService.Layout layout) {
            return base.Channel.Update(layout);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(TicketManagement.WPF.WCF.LayoutService.Layout layout) {
            return base.Channel.UpdateAsync(layout);
        }
    }
}
