//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.ASP.WCF.PurchaseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.PurchaseService.IPurchaseService")]
    public interface IPurchaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetAll", ReplyAction="http://tempuri.org/IPurchaseService/GetAllResponse")]
        DataPresenter.Entity.Purchase[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetAll", ReplyAction="http://tempuri.org/IPurchaseService/GetAllResponse")]
        System.Threading.Tasks.Task<DataPresenter.Entity.Purchase[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/Delete", ReplyAction="http://tempuri.org/IPurchaseService/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/Delete", ReplyAction="http://tempuri.org/IPurchaseService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/Get", ReplyAction="http://tempuri.org/IPurchaseService/GetResponse")]
        DataPresenter.Entity.Purchase Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/Get", ReplyAction="http://tempuri.org/IPurchaseService/GetResponse")]
        System.Threading.Tasks.Task<DataPresenter.Entity.Purchase> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetForUser", ReplyAction="http://tempuri.org/IPurchaseService/GetForUserResponse")]
        DataPresenter.Entity.Purchase[] GetForUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseService/GetForUser", ReplyAction="http://tempuri.org/IPurchaseService/GetForUserResponse")]
        System.Threading.Tasks.Task<DataPresenter.Entity.Purchase[]> GetForUserAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseServiceChannel : TicketManagement.ASP.WCF.PurchaseService.IPurchaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseServiceClient : System.ServiceModel.ClientBase<TicketManagement.ASP.WCF.PurchaseService.IPurchaseService>, TicketManagement.ASP.WCF.PurchaseService.IPurchaseService {
        
        public PurchaseServiceClient() {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataPresenter.Entity.Purchase[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<DataPresenter.Entity.Purchase[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public DataPresenter.Entity.Purchase Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<DataPresenter.Entity.Purchase> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public DataPresenter.Entity.Purchase[] GetForUser(int userId) {
            return base.Channel.GetForUser(userId);
        }
        
        public System.Threading.Tasks.Task<DataPresenter.Entity.Purchase[]> GetForUserAsync(int userId) {
            return base.Channel.GetForUserAsync(userId);
        }
    }
}
