//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.WPF.WCF.VenueService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/DataPresenter.Entity")]
    [System.SerializableAttribute()]
    public partial class Venue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.VenueService.IVenueService")]
    public interface IVenueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Delete", ReplyAction="http://tempuri.org/IVenueService/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Delete", ReplyAction="http://tempuri.org/IVenueService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Get", ReplyAction="http://tempuri.org/IVenueService/GetResponse")]
        TicketManagement.WPF.WCF.VenueService.Venue Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Get", ReplyAction="http://tempuri.org/IVenueService/GetResponse")]
        System.Threading.Tasks.Task<TicketManagement.WPF.WCF.VenueService.Venue> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/GetAll", ReplyAction="http://tempuri.org/IVenueService/GetAllResponse")]
        TicketManagement.WPF.WCF.VenueService.Venue[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/GetAll", ReplyAction="http://tempuri.org/IVenueService/GetAllResponse")]
        System.Threading.Tasks.Task<TicketManagement.WPF.WCF.VenueService.Venue[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Save", ReplyAction="http://tempuri.org/IVenueService/SaveResponse")]
        int Save(TicketManagement.WPF.WCF.VenueService.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Save", ReplyAction="http://tempuri.org/IVenueService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(TicketManagement.WPF.WCF.VenueService.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Update", ReplyAction="http://tempuri.org/IVenueService/UpdateResponse")]
        bool Update(TicketManagement.WPF.WCF.VenueService.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVenueService/Update", ReplyAction="http://tempuri.org/IVenueService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(TicketManagement.WPF.WCF.VenueService.Venue venue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVenueServiceChannel : TicketManagement.WPF.WCF.VenueService.IVenueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VenueServiceClient : System.ServiceModel.ClientBase<TicketManagement.WPF.WCF.VenueService.IVenueService>, TicketManagement.WPF.WCF.VenueService.IVenueService {
        
        public VenueServiceClient() {
        }
        
        public VenueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VenueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VenueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VenueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public TicketManagement.WPF.WCF.VenueService.Venue Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<TicketManagement.WPF.WCF.VenueService.Venue> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public TicketManagement.WPF.WCF.VenueService.Venue[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TicketManagement.WPF.WCF.VenueService.Venue[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public int Save(TicketManagement.WPF.WCF.VenueService.Venue venue) {
            return base.Channel.Save(venue);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(TicketManagement.WPF.WCF.VenueService.Venue venue) {
            return base.Channel.SaveAsync(venue);
        }
        
        public bool Update(TicketManagement.WPF.WCF.VenueService.Venue venue) {
            return base.Channel.Update(venue);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(TicketManagement.WPF.WCF.VenueService.Venue venue) {
            return base.Channel.UpdateAsync(venue);
        }
    }
}
