//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.ASP.WCF.DbInitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.DbInitService.IDbInitService")]
    public interface IDbInitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbInitService/Seed", ReplyAction="http://tempuri.org/IDbInitService/SeedResponse")]
        void Seed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbInitService/Seed", ReplyAction="http://tempuri.org/IDbInitService/SeedResponse")]
        System.Threading.Tasks.Task SeedAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbInitServiceChannel : TicketManagement.ASP.WCF.DbInitService.IDbInitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbInitServiceClient : System.ServiceModel.ClientBase<TicketManagement.ASP.WCF.DbInitService.IDbInitService>, TicketManagement.ASP.WCF.DbInitService.IDbInitService {
        
        public DbInitServiceClient() {
        }
        
        public DbInitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbInitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbInitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbInitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Seed() {
            base.Channel.Seed();
        }
        
        public System.Threading.Tasks.Task SeedAsync() {
            return base.Channel.SeedAsync();
        }
    }
}
